Mouha.DemoAspNetCoreGithub/Mouha.DemoAspNetCoreGithub/Controllers/CompteController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Mouha.DemoAspNetCoreGithub.Models;
using Mouha.DemoAspNetCoreGithub.Repository;

namespace Mouha.DemoAspNetCoreGithub.Controllers
{
    public class CompteController : Controller
    {
        private readonly ICompteRepository _compteRepository;

        public CompteController(ICompteRepository compteRepository)
        {
            _compteRepository = compteRepository;
        }

        [Route("signup")]
        public IActionResult SignUp()
        {
            return View();
        }

        [Route("signup")]
        [HttpPost]
        public async Task<IActionResult> SignUp(DeconnecterUserModel logingUser)
        {
            if (ModelState.IsValid)
            {
                //Ecrire code
                var result = await _compteRepository.CreationUserAsync(logingUser);
                if (!result.Succeeded)
                {
                    foreach (var errorMessage in result.Errors)
                    {
                        ModelState.AddModelError("", errorMessage.Description);
                    }

                    return View(logingUser);
                }

                ModelState.Clear();
                return RedirectToAction("ConfirmEmail", new { email = logingUser.Email});
            }
            return View(logingUser);
        }

        [Route("login")]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [Route("login")]
        public async Task<IActionResult> Login(SeConnecterUserModel connecterUserModel, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                var result = await _compteRepository.PasswordSignInAsync(connecterUserModel);
                if (result.Succeeded)
                {
                    if (!string.IsNullOrEmpty(returnUrl))
                    {
                        return LocalRedirect(returnUrl);
                    }
                    return RedirectToAction("Index", "Home");
                }

                if (result.IsNotAllowed)
                {
                    ModelState.AddModelError("", "Vous n'êtes pas autorisé à se connecter");
                }
                else if (result.IsLockedOut)
                {
                    ModelState.AddModelError("", "Votre compte est verrouillé. Ressayé plus tard.");
                }
                else
                {
                    ModelState.AddModelError("", "les informations d'identification invalides");
                }
                
            }

            return View(connecterUserModel);
        }

        [Route("logout")]
        public async Task<IActionResult> Logout()
        {
            await _compteRepository.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }

        [Route("modifier-motdepasse")]
        public IActionResult ModifierMotdepasse()
        {    
            return View();
        }

        [Route("modifier-motdepasse")]
        [HttpPost]
        public async Task<IActionResult> ModifierMotdepasse(ModifierMotdepasseModel model)
        {
            if (ModelState.IsValid)
            {
                //Ecrire code
                var result = await _compteRepository.ModifierMotdepasseAsync(model);
                if (result.Succeeded)
                {
                    ViewBag.EstReussi = true;
                    ModelState.Clear();
                    return View();
                }

                foreach (var erreur in result.Errors)
                {
                    ModelState.AddModelError("", erreur.Description);
                }
            }

            return View(model);
        }

        [HttpGet("confirm-email")]
        public async Task<IActionResult> ConfirmEmail(string uid, string token, string email)
        {
            EmailConfirmModel model = new EmailConfirmModel
            {
                Email = email
            };

            if (!string.IsNullOrEmpty(uid) && !string.IsNullOrEmpty(token))
            {
                token = token.Replace(' ', '+');
                var result = await _compteRepository.ConfirmEmailAsync(uid, token);
                if (result.Succeeded)
                {
                    model.EmailVerifie = true;
                }
            }

            return View(model);
        }

        [HttpPost("confirm-email")]
        public async Task<IActionResult> ConfirmEmail(EmailConfirmModel model)
        {
            var user = await _compteRepository.GetUserByEmailAsync(model.Email);
            if (user != null)
            {
                if (user.EmailConfirmed)
                {
                    model.EmailVerifie = true;
                    return View(model);
                }

                await _compteRepository.GenerateEmailConfirmationTokenAsync(user);
                model.EmailEnvoye = true;
                ModelState.Clear();
            }
            else
            {
                ModelState.AddModelError("", "Quelque chose ne marche pas");
            }
            return View();
        }

        [AllowAnonymous, HttpGet("forgot-password")]
        public IActionResult ForgotPassword()
        {
            return View();
        }

        [AllowAnonymous, HttpPost("forgot-password")]
        public async Task<IActionResult> ForgotPassword(ForgotPasswordModel model)
        {
            if (ModelState.IsValid)
            {
                //Code
                var user = await _compteRepository.GetUserByEmailAsync(model.Email);
                if (user != null)
                {
                   await _compteRepository.GenerateForgotPasswordTokenAsync(user);
                }

                ModelState.Clear();
                model.EmailEnvoye = true;
            }
            return View(model);
        }

        [AllowAnonymous, HttpGet("reset-password")]
        public IActionResult ResetPassword(string uid, string token)
        {
            ResetPasswordModel model = new ResetPasswordModel
            {
                Token = token,
                UserId = uid
            };
            return View(model);
        }

        [AllowAnonymous, HttpPost("reset-password")]
        public async Task<IActionResult> ResetPassword(ResetPasswordModel model)
        {
            if (ModelState.IsValid)
            {
                //Code
                model.Token = model.Token.Replace(' ', '+');
                var result = await _compteRepository.ResetPasswordAsync(model);
                if (result.Succeeded)
                {
                    ModelState.Clear();
                    model.EstSucces = true;
                }

                foreach (var erreur in result.Errors)
                {
                    ModelState.AddModelError("", erreur.Description);             
                }
       
            }
            return View(model);
        }
    }
}

Mouha.DemoAspNetCoreGithub/Mouha.DemoAspNetCoreGithub/Views/Compte/ConfirmEmail.cshtml
@model EmailConfirmModel
@{
    ViewData["Title"] = "ConfirmEmail";
}

<div class="continer">
    <div class="row text-center">
        <div class="col-md-4">
            @if (Model.EmailVerifie == true)
            {
                <div class="alert alert-success" role="alert">
                    <p>Votre email est vérifié avec succès.</p>
                </div>
            }
            else
            {
                @if (Model.EmailEnvoye)
                {
                    <p>Email envoyé dans votre enregistrement id email</p>
                }
                else
                {
                    <p>Nous avons envoyé un identifiant d'email. Cliquez sur le lien pur se connecter.</p>
                }
                <form action="/" method="post">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="Email" />
                    <p>N'avez vous pas reçu aucun e-mail supprimé par erreur?</p>
                    <div class="form-group">
                        <input type="submit" name="name" value="Confirmation du renvoi de l'email" />
                    </div>
                </form>

            }

        </div>
    </div>
</div>

Mouha.DemoAspNetCoreGithub/Mouha.DemoAspNetCoreGithub/Views/Compte/ForgotPassword.cshtml
@model Mouha.DemoAspNetCoreGithub.Models.ForgotPasswordModel

@{
    ViewData["Title"] = "ForgotPassword";
}

<div class="container">
    <h4>ForgotPasswordModel</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">

            @if (Model?.EmailEnvoye == true)
            {
                <div class="alert alert-success" role="alert">
                    <p> Nous avons envoyé un email dans votre boîte de reception.</p>
                </div>
            }
            else
            {
                <p>Si vous avez oublié, vous pouvez le réinitialiser. </p>
                <form asp-action="ForgotPassword">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Email" class="control-label"></label>
                        <input asp-for="Email" class="form-control" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <input type="submit" value="Continue" class="btn btn-primary" />
                    </div>
                </form>
            }


        </div>

    </div>

    <div>
        <a asp-action="Login" asp-controller="Compte">Login</a>
    </div>
</div>

Mouha.DemoAspNetCoreGithub/Mouha.DemoAspNetCoreGithub/Views/Compte/Login.cshtml
@model Mouha.DemoAspNetCoreGithub.Models.SeConnecterUserModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Login</title>
    <environment include="Development">
        <link href="~/lib/twitter-bootstrap/css/bootstrap.css" rel="stylesheet" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet"
              href="http://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
              asp-fallback-href="~/lib/twitter-bootstrap/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only"
              asp-fallback-test-property="position"
              asp-fallback-test-value="absolute"
              integrity=""
              crossorigin="anonymous">
    </environment>
</head>
<body>

    <div class="container">
        <h4>Se connecter</h4>
        <hr />
        <div class="row">
            <div class="col-md-4">
                <form method="post">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Email" class="control-label"></label>
                        <input asp-for="Email" class="form-control" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Motdepasse" class="control-label"></label>
                        <input asp-for="Motdepasse" class="form-control" />
                        <span asp-validation-for="Motdepasse" class="text-danger"></span>
                    </div>
                    <div class="form-group form-check">
                        <label class="form-check-label">
                            <input class="form-check-input" asp-for="RemenberMe" /> @Html.DisplayNameFor(model => model.RemenberMe)
                        </label>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Login" class="btn btn-primary" />
                    </div>
                </form>
            </div>

            <div class="col-md-8">
                <img src="~/images/login.png" class="img-fluid" />
            </div>
        </div>
        

        <div>
            <p>Cliquer <a asp-action="ForgotPassword" asp-controller="Compte">Mot de passe oublié</a></p>

            <p>Cliquer <a asp-action="signup" asp-controller="Compte">ici</a> pour se déconnecter</p>
        </div>

    </div>

</body>
</html>

Mouha.DemoAspNetCoreGithub/Mouha.DemoAspNetCoreGithub/Views/Compte/ModifierMotdepasse.cshtml
@model Mouha.DemoAspNetCoreGithub.Models.ModifierMotdepasseModel

@{
    ViewData["Title"] = "ModifierMotdepasse";
}

<div class="container">
        <h4 class="display-4 text-center">Changement de mot de passe</h4>
        <hr />

        <div class="row">
            <div class="col-md-4 offset-4"> 
                @if (ViewBag.EstReussi == true)
                {
                    <div class="alert alert-success" role="alert" >
                        Le mot de passe a été modifié avec succès
                    </div>
                }
                <form asp-action="ModifierMotdepasse">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="MotdepasseCourant" class="control-label"></label>
                        <input asp-for="MotdepasseCourant" class="form-control" />
                        <span asp-validation-for="MotdepasseCourant" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="NouveauMotdepasse" class="control-label"></label>
                        <input asp-for="NouveauMotdepasse" class="form-control" />
                        <span asp-validation-for="NouveauMotdepasse" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ConfirmerMotdepasse" class="control-label"></label>
                        <input asp-for="ConfirmerMotdepasse" class="form-control" />
                        <span asp-validation-for="ConfirmerMotdepasse" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Modifier" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>
</div>

Mouha.DemoAspNetCoreGithub/Mouha.DemoAspNetCoreGithub/Views/Compte/ResetPassword.cshtml
@model Mouha.DemoAspNetCoreGithub.Models.ResetPasswordModel

@{
    ViewData["Title"] = "ResetPassword";
}
<div class="container">

    <h1 class="display-4">Reset password</h1>

    <hr />
    <div class="row">
        <div class="offset-4 col-md-4">
            @if (Model?.EstSucces == true)
            {
                <div class="alert alert-success" role="alert">
                    <p>
                        You have updated your password successfully.
                    </p>
                </div>
            }
            else
            {
                <form asp-action="ResetPassword">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="UserId" class="form-control" />
                    <input type="hidden" asp-for="Token" class="form-control" />
                    <div class="form-group">
                        <label asp-for="NouveauMotdepasse" class="control-label"></label>
                        <input asp-for="NouveauMotdepasse" class="form-control" />
                        <span asp-validation-for="NouveauMotdepasse" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ConfirmNouveauMotdepasse" class="control-label"></label>
                        <input asp-for="ConfirmNouveauMotdepasse" class="form-control" />
                        <span asp-validation-for="ConfirmNouveauMotdepasse" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Reset password" class="btn btn-primary" />
                    </div>
                </form>
            }

        </div>
    </div>

</div>

@*@{
        ViewData["Title"] = "ResetPassword";
    }
    <div class="container">
        <div class="row">

            <h4>ResetPasswordModel</h4>
            <hr />
            <div class="offset-4 col-md-4">
                @if (Model?.EstSucces == true)
                {
                    <div class="alert alert-success" role="alert">
                        <p> Vous avez modifié votre mot de passe avec succès.</p>
                    </div>
                }
                else
                {
                    <form asp-action="ResetPassword">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <input type="hidden" asp-for="UserId" class="form-control" />
                        <input type="hidden" asp-for="Token" class="form-control" />
                        <div class="form-group">
                            <label asp-for="NouveauMotdepasse" class="control-label"></label>
                            <input asp-for="NouveauMotdepasse" class="form-control" />
                            <span asp-validation-for="NouveauMotdepasse" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="ConfirmNouveauMotdepasse" class="control-label"></label>
                            <input asp-for="ConfirmNouveauMotdepasse" class="form-control" />
                            <span asp-validation-for="ConfirmNouveauMotdepasse" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Reset password" class="btn btn-primary" />
                        </div>
                    </form>
                }
            </div>
        </div>

        <div>
            <a asp-action="Index">Back to List</a>
        </div>
    </div>*@

Mouha.DemoAspNetCoreGithub/Mouha.DemoAspNetCoreGithub/Views/Compte/SignUp.cshtml
@model Mouha.DemoAspNetCoreGithub.Models.DeconnecterUserModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>SignUp</title>
    <environment include="Development">
        <link href="~/lib/twitter-bootstrap/css/bootstrap.css" rel="stylesheet" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet"
              href="http://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
              asp-fallback-href="~/lib/twitter-bootstrap/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only"
              asp-fallback-test-property="position"
              asp-fallback-test-value="absolute"
              integrity=""
              crossorigin="anonymous">
    </environment>

</head>
<body>

    <div class="container">
        <div class="row">

            <div class="col-md-4">
                <h4>Page loging Utilisateur</h4>
                <hr />
                <form asp-action="SignUp">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Prenom" class="control-label"></label>
                        <input asp-for="Prenom" class="form-control" />
                        <span asp-validation-for="Prenom" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Nom" class="control-label"></label>
                        <input asp-for="Nom" class="form-control" />
                        <span asp-validation-for="Nom" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Email" class="control-label"></label>
                        <input asp-for="Email" class="form-control" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Password" class="control-label"></label>
                        <input asp-for="Password" class="form-control" />
                        <span asp-validation-for="Password" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ConfirmPassword" class="control-label"></label>
                        <input asp-for="ConfirmPassword" class="form-control" />
                        <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-primary" />
                    </div>
                </form>
            </div>
            <div class="col-md-8">
                <img src="~/images/signup.png" class="img-fluid" />
            </div>
        </div>

        <div>
            <p>Cliquer <a asp-action="Login" asp-controller="Compte">ici</a> pour se connecter</p>
        </div>

    </div>
</body>
</html>